ALTER TABLE "execution" ADD COLUMN "workflowSnapshot" JSONB;

ALTER TABLE "node" ADD COLUMN "disabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "node" ADD COLUMN "onError" TEXT NOT NULL DEFAULT 'STOP_WORKFLOW';
ALTER TABLE "node" ADD COLUMN "retryOnFail" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "node" ADD COLUMN "maxTries" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "node" ADD COLUMN "waitBetweenTries" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "node" ADD COLUMN "alwaysOutputData" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "node" ADD COLUMN "notes" TEXT;
